# INTRODUCTION TO PYTHON

### CONTENT
1. Introduction
2. Variables and data structures 
3. Conditional and iteractive structures
4. Functions 
5. Introduction to NumPy 
6. Introduction to Pandas
7. Exercises

## 1. Introduction

<img src="Figures/Jupyter.png" alt="Drawing" style="width: 100px;"/>

Jupyter notebooks is an environment (IDE) that allows to interleave text content (to be called 'Markdown' cell) with Python code ('Code' cell) that can be executed cell by cell as shown in the following examples.

The basic commands to start using Jupyter Notebooks are:

<img src="Figures/menu-vEng.png" alt="Drawing" style="width: 850px;"/>

* `Shift+Enter`: Execute cell and select next cell.
* `Alt+Enter`: Execute cell and insert a new cell.
* `ESC`: to start 'command' mode. Once in this mode:
    * `H` list of commands
    * `A` insert cell below
    * `B` inster cell above
    * `D,D` D twice to delete cell
    * `Y` change cell type to 'Code'
    * `M` change cell type to 'Markdown'
    * `Enter` go back to 'edit' mode.

#### Execute the cell below using any of the possible commands

In [1]:
3 + 4 + 9

16

In [2]:
# Python code example
# Change values a and b, and observe the result when executing the cell 

a=87
b=34
c=a+b

print('The result of adding {} and {} is {}.'.format(a,b,c))

The result of adding 87 and 34 is 121.

### 1.1. Variables and data structures

Variables in Python are created once they are defined, that is, when a value is assigned to the variable for the first time (using the <code> = </code> operator). For this reason, variables (and their type) do not need to be declared in Python. 

The main types of variables that can be found are:
* **Numeric**
    * **Integer:** Positive and negative natural numbers.
    * **Float:** Real numbers.
    * **Complex:** Complex numbers. The imaginary part is multiplied by `j` to represent the root of `-1` Números complejos.
* **Boolean**
    These are variables that can take True or False as a value, represented in Python by `True` and `False` using uppercase for the initial letter.
* **Data structures (data sequences)**.
    Ordered list of values of the same or different type. In Python they exist:
    * **String:** text strings
    * **List:** ordered sets of elements
    * **Tuple:** ordered and immutable sets of elements
    * **Dictionary:** sets of elements characterized by an identifier and a value

There are some general rules for variable names:
+ Only letters, numbers and "underscores" (_) are used.
+ NO spaces are used anywhere in the name
+ The name cannot start with a number
+ Uppercase letters are treated as different from lowercase letters (i.e., Python is case-sensitive)

In [3]:
# The name can't start with a number
3a = 10

SyntaxError: invalid syntax (173782835.py, line 2)

Whenever a variable is created or modified, Python interprets what type of variable it is. When a new value is assigned to an existing object (*dynamic typing*), the previous values of that object are cleared from the computer's memory. The first value of **a** is the real number 13.0, but after a new assignment:

In [ ]:
# Dynamic typing
a = 13.0
a = 'b'
print(a)

The ``type()`` function displays the TYPE of the data we introduce:

In [ ]:
x = True
print(type(x))

name = 'Vinicius'
print(type(name))

age = 32
print(type(age))

money = 5.5
print(type(money))

list0 = ['Vinicius', 32, 5.5]
print(type(list0))

We can print the elements in the list or any variables using the command `print` and `.format` or simply summing strings:

In [ ]:
print('My name is {}, I have {} years old and {} euros.'.format(list1[0], list1[1], list1[2]))

#or

print('My name is {}, I have {} years old and {} euros.'.format(name, age, money))

#or

print('My name is '+ name + ', I have ' + str(age) + ' years old and ' + str(money) + ' euros')

### 1.2 Types and basic operators

The basic operators in Python are:

+ Addition (also for strings, tuples or lists): <code>a + b</code>
+ Subtraction: <code>a - b</code>
+ Multiplication (also for strings, tuples and lists): <code>a * b</code>
+ Division: <code>a / b</code>
+ Integer division: <code>a // b</code>
+ Remainder: <code>a % b</code>
+ Exponential: <code>a ** b</code>
+ Assignment: <code>=</code>, <code>-=</code>, <code>+=</code>,<code>/=</code>,<code>*=</code>, <code>%=</code>, <code>//=</code>, <code>**=</code>
+ Boolean comparisons: <code>==</code>, <code>!=</code>, <code><</code>,<code>></code>,<code><=</code>, <code>>=</code>
+ Boolean operations: <code>and</code>, <code>or</code>, <code>not</code>
+ Operations to check belongingness: <code>in</code>, <code>not in</code>
+ Operations to identify objects: <code>is</code>, <code>is not</code>
<!-- + Bitwise operators (or, xor, and, complement): <code>|</code>, <code>^</code>, <code>&</code>, <code>~</code> -->
<!-- + Left and right bit shift: <code><<</code>, <code>>></code> -->

In [ ]:
# Boolean or logic operators

a = 7
b = 2

print(a>b and b<a)

print(a==7 and b==5)

print(a==7 or b==5)

In [ ]:
# Operators to check belongingness

my_list = [1, 3, 2, 7, 9, 8, 6]
print(4 in my_list)
print(8 in my_list)

In [ ]:
# Operators to identify objects

a = 7
b = 2  
c = 7
print(a is c)
print (a is not b)
print (a is not c)

### 1.3 Python as a calculator

Python has a concise notation for arithmetic that closely resembles the traditional way of writing operations.

In [ ]:
a = 3+2
b= 3.5 * -8
c = 10/6
print(a, b, c, 10./6.)

For more complex operations, we need to use other packages such as `math` and `numpy`.

In [ ]:
import numpy as np   # only executed if the library hasn't been imported previously
print(np.pi)
print(np.sin(1.8))
print(np.arccos(0.8))

## 2 Data structures

### 2.1 Strings or text strings

Text in Python is treated as a list of characters. Thus, the methodology that applies to the treatment of lists can be applied to text strings.

In [ ]:
print("This is 'an example' of how to use quotation marks inside a text that is written between double quotation marks")
print('Here is "another example" but this time inverted')

The '+' operator can be used to join character strings:

In [ ]:
a = 'He'
b = 'llo'
c = a+b+'!'
print(c)

To access only a part of a list or, in this case, of a *string*, the technique called **slicing** is used. The format to follow to access only a part of the string is as follows:

### <center>variable_name[first_element_index:final_index:step]</center>

Where the operation of the indexes can be seen in the following picture:

![Slicing1](Figures/slicing1.png)

In [ ]:
#Example
a = 'abcdef'

print('Everything: {}'.format(a[:]))
print('First value: {}'.format(a[0]))
print('Second to end: {}'.format(a[2:]))
print('First 3: {}'.format(a[:3]))
print('Second to Fourth: {}'.format(a[2:4]))
print('All odd positions: {}'.format(a[::2]))
print('All even positions: {}'.format(a[1::2]))

In the case of *strings*, there are default methods in Python that can be useful. For example the following functions:
- len: returns the length of the text.
- str: converts a number into a string.
- reverse: returns the text backwards.

We can also use string-specific methods:
- lower: converts all text to lowercase.
- upper: converts all text to uppercase.
- capitalize: capitalizes the first letter of the string.
- split(delimiter): returns a list of substrings separated by the specified delimiter (see examples below).

In [5]:
text='We are going to test the Strings Functions and Methods!'
print(len(text))
print(text.lower())
print(text.split(' '))

# Return the 4th word of the text in all capital letters
print(text[7:12].upper())

55
we are going to test the strings functions and methods!
['We', 'are', 'going', 'to', 'test', 'the', 'Strings', 'Functions', 'and', 'Methods!']
GOING

### 2.2 Lists

Lists are a Python type used to group objects of other types (even lists!). For example a list of numbers, of floats, of strings, of other lists, and so on. 

Lists, like strings, can use the *slicing* methodology.

In [ ]:
# Create list
my_list = [0,5,'6',34,'Hello']
my_list

In [ ]:
# Access to an element of a list
a = my_list[2]
a

In [ ]:
# Change an element of a list
my_list[-1]='Bye'
my_list

In [ ]:
# We can have lists of lists
my_list=[45,[3,5,6],'word',34.6,['a','b','c']]
print(my_list)
print(my_list[1])
print(my_list[1][2])
my_list[4][2]

For lists there are also default Python functions and methods that can be useful. For example the following functions:
- len: returns the length of the list.
- list: create list

To use a function, call function_name(variable_name).

We can also use list-specific methods:
- append: add element to the end of the list.
- insert: add an element in a particular position.
- pop: remove the last element of the list.
- remove: remove a particular element.
- sort: sort the list

To use a method, call variable_name.method_name.

In [ ]:
my_list=['first','hello','test','bye','animals','master']
print(my_list)

my_list.append('last')
print(my_list)

my_list.insert(1,'second')
print(my_list)

my_list.pop()
print(my_list)

my_list.remove('test')
print(my_list)

my_list.sort()
print(my_list)

### 2.3 Dictionaries

A dictionary is another way of grouping data where an element can be accessed through its *key*. For example:

In [7]:
this_installation = {
    'Power': 10,
    'Type': 'Solar',
    'Construction_year':2012
}

In [8]:
this_installation['Type']

'Solar'

Another example could be:

In [21]:
dict = {"Installation_1": "Solar", "Installation_2": "Wind", "Installation_3": "Wind", "Installation_4": "Hidraulyc",
        "Installation_5": "Solar",}
print(dict)

{'Installation_1': 'Solar', 'Installation_2': 'Wind', 'Installation_3': 'Wind', 'Installation_4': 'Hidraulyc', 'Installation_5': 'Solar'}

To access, modify or add an item, it can be done in a similar way to the lists:

In [22]:
# Access
dict["Installation_1"]

'Solar'

In [23]:
# Modify
print(dict)
dict["Installation_1"]="Wind"
print(dict)

{'Installation_1': 'Solar', 'Installation_2': 'Wind', 'Installation_3': 'Wind', 'Installation_4': 'Hidraulyc', 'Installation_5': 'Solar'}
{'Installation_1': 'Wind', 'Installation_2': 'Wind', 'Installation_3': 'Wind', 'Installation_4': 'Hidraulyc', 'Installation_5': 'Solar'}

In [24]:
# Add
print(dict)
dict["Installation_6"]="Solar"
print(dict)

{'Installation_1': 'Wind', 'Installation_2': 'Wind', 'Installation_3': 'Wind', 'Installation_4': 'Hidraulyc', 'Installation_5': 'Solar'}
{'Installation_1': 'Wind', 'Installation_2': 'Wind', 'Installation_3': 'Wind', 'Installation_4': 'Hidraulyc', 'Installation_5': 'Solar', 'Installation_6': 'Solar'}

Dictionaries can contain all types (int, floats, lists, other dictionaries, etc.).

In [27]:
dict = {"Installation_1": ["Solar", '10 MW'], "Installation_2": ["Wind", '15 MW'], "Installation_3": ["Solar", '18 MW'],
        "Installation_4": ["Hydraulic", '12 MW'], "Installation_5": ["Solar", '23 MW'], "Installation_6": ["Wind", '8 MW'],
        "Installation_7": ["Solar", '11 MW'], "Installation_8": ["Hydraulic", '11 MW']}
dict

{'Installation_1': ['Solar', '10 MW'],
 'Installation_2': ['Wind', '15 MW'],
 'Installation_3': ['Solar', '18 MW'],
 'Installation_4': ['Hydraulic', '12 MW'],
 'Installation_5': ['Solar', '23 MW'],
 'Installation_6': ['Wind', '8 MW'],
 'Installation_7': ['Solar', '11 MW'],
 'Installation_8': ['Hydraulic', '11 MW']}

In [28]:
dict['Installation_3'][1]

'18 MW'

In [29]:
# Changing power of installation 4 to 15 MW modifying the dictionary!

dict['Installation_4'][1]='15 MW'
print(dict['Installation_4'])

['Hydraulic', '15 MW']

### 2.4 Tuples

Tuples are lists **that cannot be modified.**

Their syntax is the same as lists, but to write a tuple you use parentheses and not square brackets.

In [31]:
mysupertuple = ('Solar', 'Wind', 'Hydraulic', 'Gas', 'Nuclear', 'NoMoreCoal')
print(type(mysupertuple), mysupertuple[4:])

<class 'tuple'> ('Nuclear', 'NoMoreCoal')

In [32]:
#CANNOT BE MODIFIED!
mysupertuple[0]='PV'

TypeError: 'tuple' object does not support item assignment

## 3. Conditional and iteractive structures

### 3.1 Conditional control structures (if)

Conditional control structures allow you to execute one part of the code or another depending on the evaluation of one or several boolean conditions of YES or NO (**<code>TRUE</code>** o **<code>FALSE</code>**).

In Python, conditional control structures are defined by the words **<code>if</code>**, **<code>elif</code>** y **<code>else</code>**.

- **<code>if CONDICION:</code>** if the conditional expression is met, the following code block is executed.
- **<code>elif CONDICION:</code>** otherwise, if this conditional expression is met, this other code block is executed.
- **<code>else:</code>** otherwise, this code block is executed without evaluating any condition.


The condition is usually evaluated by the following relational operators <code> <, <=, ==, >=, >, != </code>.

The part of code inside an **<code>if</code>** cannot be empty, but if for some reason an if statement must be created without content, the **<code>pass</code>** statement can be used to prevent an error from occurring.

In [ ]:
# Example

celsius = 0
fahrenheit = 9.0 /5.0 * celsius + 32

print("Temperature in Fahrenheit is", fahrenheit)

if fahrenheit > 90:
    print("It is hot")
elif fahrenheit < 30:
    print("It is cold")
else: print("It is neither hot nor cold")

The conditional structure can also be expressed in a single line as follows, depending on whether one, two or more conditions are involved:

In [ ]:
#Example

a = 330
b = 330

# with one only condition:
if a > b: print("a is larger than b")
    
# with two conditions:
print("a is larger") if a > b else print("a is not larger")

# with 3 conditions:
print("A") if a > b else print("=") if a == b else print("B")

####  <font color='red'>Try it yourself!</font> 

<font color='red'>Create a code to identify whether the variable **<code>number</code>** is a positive, negative, or 0 value. Store the result in a variable called **<code>sign</code>**. </font>

In [ ]:
number = 2

###############################
if number > 0:
    sign = 'positive'
elif number < 0:
    sign = 'negative'
else:
    sign = 'zero'

print(sign)

### 3.2 Iterative control structures (for & while)

Iterative control structures (also called loops) allow the same code to be executed repeatedly as long as a condition is met.

There are two types of iterative control structures:

* For
* While

The Python ``for`` statement iterates over the elements of any sequence (a list or a string for example), in the order they appear in the sequence.

The ``while`` loop allows multiple iterations to be performed based on the result of a logical expression that can result in a ``True`` or ``False`` value.

In [ ]:
# Example of for

for i in range(0,10,1):
    print(i)

In [ ]:
# Example of while

i=0
while i < 10 :
    print(i)
    i= i+1

In addition, loops with ``for`` or ``while`` can be combined with conditional ``if`` structures to create more complex structures.

With the ``break`` statement we can stop the loop before it has gone through all elements.

With the ``continue`` statement we can stop the current iteration of the loop (in both ``for`` and ``while``) and continue with the next one.

####  <font color='red'>Try it yourself!</font> 

<font color='red'>Create a code that calculates the average value of a list of **<code>numbers</code>** using a `for` loop.

In [33]:
# Exercise: calculating the average value of a list with a for

numbers=[1,2,3,4]

#####################

sum_numbers = 0
for n in numbers:
    sum_numbers += n

average = sum_numbers/len(numbers)
print(sum_numbers, average)

10 2.5

### 3.3 Lists (or dictionary) comprehensions

List comprehensions are a way of fitting a ``for`` loop, an ``if`` statement, and an assignment all on a single line.

A list comprehension consists of the following parts:

+ An input sequence
+ A variable representing members of the input sequence
+ An optional expression
+ An output expression that produces elements of the output list from members of the input sequence that satisfy the predicate

In [34]:
# Example
num = [1, 4, -5, 10, -7, 2, 3, -1]
squared = []
for i in num:
     if i > 0:
        squared.append(i**2)
print(type(squared), squared)

# This for can be rewritten as follows:
# In an iteration, it first checks if the if is TRUE and then performs the calculation
squared = [x**2 for x in num if x > 0] 
print(type(squared), squared)

<class 'list'> [1, 16, 100, 4, 9]
<class 'list'> [1, 16, 100, 4, 9]

This compact way of expressing loops can also be used to iterate within lists. Below are different ways to join the values of two lists using zip or nested fors.

In [35]:
list1 = ['a','b','c','d']
list2 = [1,2,3,4]

# Create a list with nested fors:
print ([(i,j) for i in list1 for j in list2])

# Create a list using zip:
print ([(i,j) for i,j in zip(list1,list2)])

# Cereate a dictionary using zip:
print ({i:j for i,j in zip(list1,list2)})

[('a', 1), ('a', 2), ('a', 3), ('a', 4), ('b', 1), ('b', 2), ('b', 3), ('b', 4), ('c', 1), ('c', 2), ('c', 3), ('c', 4), ('d', 1), ('d', 2), ('d', 3), ('d', 4)]
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]
{'a': 1, 'b': 2, 'c': 3, 'd': 4}

## 4. Functions
A function is a block of code with an associated name, which receives zero or more arguments as input, follows a sequence of statements where the desired operations are executed and returns a value and/or performs a task. This code block can be called multiple times as needed.

In Python there are a number of functions built into the language by default, but you can also create user-defined functions to use in your own programs. 

The complete list of default built-in functions can be found at:
www.w3schools.com/python/python_ref_functions.asp

In [38]:
# Example of an integrated function in Python

# The input() function allows us to assign a value entered by the user to a variable

a = input()

print('The variable introduced has been ' + a)

asd@312
The variable introduced has been asd@312

To create a function in Python, you must use the word ``def`` to define the function. The syntax for a function definition in Python is:

<code>*def* function_name(input_parameter_list):
    function_statements
    *return* [expression_to_return]</code>

Where:
* function_name: is the name of the function.
* input_parameter_list: is the list of parameters that a function can receive, separated by comma.
* function_statements: is the block of statements in Python source code that perform a given operation.
* expression_to_return: is the expression or variable that returns the return statement.

In [39]:
# Example: function to set the first value of a list to 0

def change_first_element(list):
    list[0]=0 #it returns none!

numbers=[1,2,3,4]
change_first_element(numbers)
print(numbers)

[0, 2, 3, 4]

#### Example: greatest common denominator (GCD)

The common denominator of two positive integers $a$ and $b$ is the greatest common divisor between $a$ and $b$ . The Euclidean algorithm is an iterative method for computing the greatest common denominator of two integers. In pseudocode it would be:

+ If $a<b$, change $a$ and $b$.
+ Divide $a$ by $b$ and obtain the residue, $r$. 
+ If $r=0$, the value $b$ is GCD of $a$ and $b$.
+ If $r \neq 0$, iterate again replacing $a$ by $b$ and replacing $b$ by $r$.

In [42]:
def GCD(a,b):
    r = 1
    while r != 0:
        if a<b:
            c=a
            a=b
            b=c
        r = a%b 
        if r == 0:
            return b
        else:
            a = b
            b = r

GCD(100,16)

4

####  <font color='red'>Try it yourself!</font> 

<font color='red'>Create a function to calculate the factorial of an integer. The factorial of a non-negative integer $n$ is the product of all positive integers less than or equal to $n$.</font>

In [41]:
#########################################

def fact_1(n):
    factorial_total = 1
    while n > 1:
        factorial_total *= n
        n -= 1
    return factorial_total

fact_1(5)

# from math import factorial
# factorial(5)

120

### 4.1 Arguments and parameters of functions

When defining a function, the values that are received are called parameters, while during the call, the values that are sent are called arguments.

By default, a function must be called with the correct number of arguments. If the function expects 2 arguments, you must call the function with 2 arguments.

#### Arguments per position

When arguments are sent to a function, by default they are received in order in the defined parameters, known as arguments by position. In the example above (GCD), argument 100 is position 0, which corresponds to the parameter of function a, while argument 16 is position 1, which corresponds to the parameter of function b.

#### Arguments by name

However, it is possible to skip the order of the parameters if you indicate during the call what value each parameter has from its name.

In [ ]:
GCD(b=100,a=16)

#### Default parameters

To avoid error messages when a function is not called with the required arguments, you can define default parameters within a function.

In [ ]:
def GCD(a=None,b=None):
    if a == None or b == None:
        print ("Error, you must send two numbers to the function.")
        return
    r = 1
    while r != 0:
        if a<b:
            c=a
            a=b
            b=c
        r = a%b 
        if r == 0:
            return b
        else:
            a = b
            b = r

GCD()

#### ndeterminate parameters ``*args`` y ``**kwargs``

Sometimes it is not known in advance how many items need to be sent to a function.

If you do not know how many arguments per item will be passed to a function, you add a * before the parameter name in the function definition. By convention, the parameter name ``*args`` is usually used. In this way, the function will receive a tuple of arguments and can access the items accordingly.

Similarly, if it is not known how many arguments by name will be passed to a function, two ** are added before the parameter name in the function definition. By convention, the parameter name ``**kwargs`` is usually used. In this way, the function will receive a dictionary of arguments and can access the elements accordingly.

In [ ]:
def super_function(*args,**kwargs):
    total = 0
    for arg in args:
        total += arg
    print ("sum => ", total)
    for kwarg in kwargs:
        print (kwarg, "=>", kwargs[kwarg])

super_function(50, -1, 1.56, 10, 20, 300, name="Peter", age=38)

## 5. Introduction to NumPy

NumPy is a Python library used to work with matrices. It also has functions for working with linear algebra or Fourier transforms. NumPy stands for Numerical Python.

<img src="Figures/NumPy_logo.png" alt="Drawing" style="width: 400px;"/>

As we have seen, in Python we already have lists that serve the purpose of working with arrays, but their processing is slow. NumPy aims to provide an array object that is up to 50 times faster than traditional Python lists, something important for data science where speed and resources are very important. In addition, they differ from lists in that NumPy arrays cannot be resized, all elements must be of the same type, and inter-array operations are allowed.

The NumPy source code can be found in this github repository https://github.com/numpy/numpy

The array object in NumPy is called ``ndarray``, it provides many support functions that make working with ``ndarray`` very easy. You can create an ndarray with NumPy with the ``.array()`` function.

To create an ndarray, we can use a list, tuple or any array object to the ``array()`` method, and it will become an ``ndarray``. You can create ``ndarrays`` of different dimensions. 0-D are just numbers, 1-D are vectors, 2-D are arrays, and so on.

The main attributes that can be used with ``ndarrays`` are:

| Attribute | Description | 
|-----------|-------------|
| ndim |number of dimensions of the matrix| 
| shape |number of elements of each dimension of the array|
| size |total number of elements in the matrix|
| dtype | type of the elements of the matrix|
| astype |to change the type of the elements of the matrix|

In [ ]:
#Example

array0 = np.array([(0,1)])

array1 = np.array(([0],[1]))

array2 = np.array([0,1])

Lets print the arrays. Whats the difference between them?

In [ ]:
print(array0)
print(array1)
print(array2)

In [ ]:
print(array0.ndim)
print(array0.shape)

print(array1.ndim)
print(array1.shape)

print(array2.ndim)
print(array2.shape)

In [ ]:
#Example of multi-dimension

array0 = np.array([(0,1),(2,3)])

array1 = np.array([(0,1,2),(3,4,5), (6,7,8)])

array2 = np.array([[(0,1,2), (3,4,5)], [(6,7,8), (9,10,11)]])

print(array0.ndim)
print(array0.shape)

print(array1.ndim)
print(array1.shape)

print(array2.ndim)
print(array2.shape)

### 5.1 Accessing values in an ndarray

An array element can be accessed by referring to its index number. Indexes in NumPy arrays start with 0, which means that the first element has index 0, and the second has index 1, etc.

To access elements of 2-D arrays we can use comma-separated integers representing the dimension and index of the element. For 3-D arrays or higher, you must add as many comma-separated integers as there are dimensions in the array.

In [ ]:
#Example

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, 1])

Slicing can also be used in ``ndarrays``. In this case: ``array[indice_primer_elemento:indice_final:step]``

In [ ]:
# Example

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# returns the index 2 of the two dimensions:

arr[:, 2]

# returns the interval between index 1 and 4 (not included) of the two dimensions:
arr[:, 1:4]

# return all elements in even positions:
arr[:, ::2]

<img src="Figures/numpy_indexing.png" alt="Drawing" style="width: 200px;"/>

####  <font color='red'>Try it yourself!</font> 

<font color='red'>Select the elements of each colored set of elements in the previous figure.</font>

In [ ]:
# Exercise: select the elements of each of the sets of elements in the previous figure:

arr = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
arr

# New array with selection of red elements:
arr2 = arr[:,2]
print(arr2)
# New array with selection of orange elements:
arr3 = arr[0, 3:5]
print(arr3)
# New array with selection of green elements:
arr4 = arr[2::2, ::2]
print(arr4)
# New array with selection of blue elements:
arr5 = arr[-2:, -2:]
print(arr5)

### For more information about NumPy

* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* https://numpy.org/learn/

# 6. Introduction to Pandas

**Pandas is one of the most important libraries in Python for Data Science!!!!** Basically it will allow us to have ``Datasets`` opened as if they were an excel spreadsheet, that is, in matrix form with two dimensions and with indexed columns and indexes.

You can learn more in the documentation: https://pandas.pydata.org/docs/

<img src="Figures/Pandas.jpg" alt="Drawing" style="width: 800px;"/>

Pandas is used to:
* Operate on the whole dataset or on a row or column (vectors) with high computational efficiency
* Helps to clean data and fix missing data
* Access subsets of data
* Add or remove columns with new features.
* Group data by characteristics.
* Very efficient in joining data from different sources.
* Work with time series.

## 6.1 Read data from a csv

Most of the time we will load the files through a .csv file. Below you can see the basic code that will be used most of the time:

In [45]:
import pandas as pd
london = pd.read_csv('Data/block_13_daily.csv')
london

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
0,MAC000113,2011-12-14,1.0910,1.065250,1.674,28,0.305397,29.827,0.262
1,MAC000113,2011-12-15,0.3710,0.546521,1.434,48,0.410120,26.233,0.119
2,MAC000113,2011-12-16,0.3205,0.534708,2.034,48,0.464431,25.666,0.129
3,MAC000113,2011-12-17,0.2570,0.421500,1.068,48,0.274387,20.232,0.115
4,MAC000113,2011-12-18,0.3985,0.565333,2.218,48,0.450712,27.136,0.134
...,...,...,...,...,...,...,...,...,...
32987,MAC005416,2014-02-24,0.0660,0.111437,0.809,48,0.126465,5.349,0.050
32988,MAC005416,2014-02-25,0.0645,0.072521,0.238,48,0.030756,3.481,0.051
32989,MAC005416,2014-02-26,0.0675,0.107917,0.343,48,0.080074,5.180,0.049
32990,MAC005416,2014-02-27,0.0910,0.104250,0.296,48,0.054844,5.004,0.047
32991,MAC005416,2014-02-28,0.0630,0.063000,0.063,1,NaN,0.063,0.063

## 6.2 Data inspection

If we want to know what dimensions this DataFrame has, we can look at its 'shape'.

In [ ]:
london.shape

There are 32992 entries and 9 characteristics for each entry.

It can be very useful to view the first or last entries of the dataset to better understand this data:

In [ ]:
london.head(10)

In [ ]:
london.tail()

If we want to know the name of the columns or indexes, we can access them:

In [ ]:
london.columns

In [ ]:
london.index

Finally, to have a very good summary, it is very useful to use the ``describe`` method.

In [ ]:
london.describe()

## 6.3 Select data

If we want to work or select only a part of the dataset, we can use **[ ]** after the dataset name, and indicate which columns we want to select.

In [ ]:
london[['day', 'energy_max']].head()

If, on the other hand, you want to select a part of the rows, it will be indicated using *slicing* as in the strings:

In [ ]:
london.iloc[0]

#### loc vs iloc

To select more specific parts (more than one column, several columns and only a few rows of these,...), indexing with loc or iloc will be used. The only difference between the two is that the first one is based on the *label* of the rows or columns, while iloc is based on the *integer* of these. With an example it is better understood:

In [ ]:
london.loc[3:5,['day', 'energy_max']]

In [ ]:
london.iloc[3:5,1:3]

Note that the index will not always be a number and can be another parameter. For example, we can set the day as the index.

## 6.4 Adding/Removing Data

To add new columns/rows we can simply use `df[new_column]` or `df.loc[new_row]` and to remove we can use the `drop` method with the parameter `axis` being 0 for row and 1 for column.

In [ ]:
# Let's create a smaller copy of our dataset:

df = london.head(5).copy()
df

In [ ]:
# Creating a new column

df['type'] = 'industrial'

# Creating a new row
df.loc[5] = 0


df

In [ ]:
# Changing the value of second row of the new column

df.loc[2, 'type'] = 'residential'
df

In [ ]:
# Removing the added column  axis=(0 for row, 1 for column)
df.drop('type', axis=1)

# removing the 5th row:
df.drop(5, axis=0)

## 6.5 Filtering data

Another way to select only a part of the dataset is to apply *Boolean indexing*, which is nothing more than applying a filter to the data. For example, we will select only those days in which the maximum energy has been greater than 1.

In [ ]:
london['energy_max'] > 5

As you can see, now we have selected those columns that meet our condition. What if we put it directly inside the dataset when we select only one part?

In [ ]:
# Here we see that all the rows are no longer displayed

london[london['energy_max'] > 5]

###  <font color='red'>Try it yourself!</font> 

<font color='red'>Obtain a summary table of the parameters for the counter with ID 'MAC000113' using the method `describe`, then use `.isna().sum()` to see if there are any missing values.</font>

In [52]:
# Obtain a DataFrame with only the values of the counter with ID 'MAC000113'
london[london['LCLid']=='MAC000113']


# Use the method .describe() to obtain the summary table of the parameters
london[london['LCLid']=='MAC000113'].describe()


# We see that there is some missing value in one of the columns. This can also be checked with the method .isna().sum()
london[london['LCLid']=='MAC000113'].isnull().sum()

LCLid            0
day              0
energy_median    0
energy_mean      0
energy_max       0
energy_count     0
energy_std       7
energy_sum       0
energy_min       0
dtype: int64

## 6.6 Interesting basic functions

Here you can see a list of the most interesting functions to look at in the documentation, with some examples:

| Function | Description |
|-----------|---------------|
| count() |Number of non-null observations|  
| sum() |Sum of values|
| mean() |Average of observations | 
| median() |Median of observations |
| min() |Minimum value|
| max() |Maximum value|
| std() |Standard deviation|
| var() | Variance|
| value_counts() | Unique values in each column - freq table|
| nunique() | Number of distinct values|
|  isnull() | Mask for null or Nan|

Practice with some of these functions.

###  <font color='red'>Try it yourself!</font> 

* What is the total energy of counter 'MAC000113'? 
* How many different counters are there? 
* What was the maximum energy value on May 15, 2013?</font>

In [51]:
# Total energy value for ID 'MAC000113'

id_MAC000113 = london[london['LCLid']=='MAC000113']
print(id_MAC000113['energy_sum'].sum())

# How many different counters are there and what are their names?

london['LCLid'].value_counts()

# What was the maximum daily energy consumption value on May 15, 2013?

london[london['day']=='2013-05-15']
london[london['day']=='2013-05-15']['energy_sum'].max()

19922.836999400002

40.5969998

In [50]:
london[london['day']=='2013-05-15']['energy_max'].max()

2.7160001

## 6.7 Sort

If you want to sort values, you can use ``sort_values``. With an example it's better understood:

In [ ]:
london.sort_values(by='energy_max', ascending= False, inplace=True)
london.head(10)

## 6.8 Group

Finally, a very useful function is the group function (group_by).

For example, imagine that you want to group all the data by counter number and take some parameter from this counter (maximum, minimum, etc.).

The result of this operation will be another dataframe with the data grouped according to a variable. In addition, you must also indicate which *aggregation* function you want to use (max, min, mean, count, sum, etc.).

Let's see an example!

In [ ]:
smart_meters = london[['LCLid','energy_max', 'energy_min', 'energy_sum']].groupby('LCLid').count()
smart_meters

# 7. Exercise 1

Using the dataset provided, write down a function that receives an input from the user with the LCLid of a counter and a year. Your function must return a `dataframe` containing all the data from that counter in that year.

In [117]:
lclid = input('Choose an id: ')
year = input('Choose an year: ')

df = london[london['LCLid']==lclid].copy()

for day in df.loc[:,'day']: 
    if day[3]!=year[3]:
        df.drop(df[df.loc[:,'day'] == day].index, inplace=True)
df

Choose an id: MAC000113
Choose an year: 2012

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
18,MAC000113,2012-01-01,0.5905,0.703104,1.925,48,0.487063,33.749,0.191
19,MAC000113,2012-01-02,0.3765,0.532958,1.137,48,0.296371,25.582,0.176
20,MAC000113,2012-01-03,0.8795,0.791083,1.629,48,0.369924,37.972,0.181
21,MAC000113,2012-01-04,0.4055,0.614542,1.742,48,0.435440,29.498,0.176
22,MAC000113,2012-01-05,0.7820,0.928708,2.477,48,0.525001,44.578,0.240
...,...,...,...,...,...,...,...,...,...
379,MAC000113,2012-12-27,0.1635,0.170021,0.257,48,0.034519,8.161,0.124
380,MAC000113,2012-12-28,0.1690,0.169021,0.245,48,0.032073,8.113,0.127
381,MAC000113,2012-12-29,0.1690,0.169062,0.281,48,0.036725,8.115,0.121
382,MAC000113,2012-12-30,0.1680,0.168937,0.268,48,0.032643,8.109,0.122
383,MAC000113,2012-12-31,0.1660,0.168417,0.267,48,0.032221,8.084,0.124

In [122]:
df.describe()

,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
count,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,0.352314,0.450611,1.325863,47.991803,0.302071,21.627546,0.134475
std,0.175095,0.159662,0.547102,0.116753,0.126176,7.666128,0.028566
min,0.154000,0.154458,0.215000,46.000000,0.027048,7.414000,0.081000
25%,0.211250,0.360865,0.954750,48.000000,0.235193,17.321500,0.117000
50%,0.295250,0.440594,1.361000,48.000000,0.319194,21.148500,0.125000
75%,0.454250,0.552667,1.722000,48.000000,0.382989,26.528000,0.136000
max,0.923500,1.098521,3.274000,48.000000,0.916933,52.729000,0.240000